def test_register(home_page, garage_page):
    sign_in = home_page.item(home_page.sign_in_button)
    sign_in.click()
    registration = home_page.item(home_page.registration_button)
    registration.click()
    fill_name = home_page.item(home_page.name_input)
    fill_name.send_keys("Vera")
    fill_last_name = home_page.item(home_page.last_name_input)
    fill_last_name.send_keys("Ivanova")
    fill_email = home_page.item(home_page.email_input)
    fill_email.send_keys("vera.i@i.ua")
    fill_password = home_page.item(home_page.password_input)
    fill_password.send_keys("Test1234!")
    fill_repeat_password = home_page.item(home_page.repeat_password)
    fill_repeat_password.send_keys("Test1234!")
    register_btn = home_page.item(home_page.register_btn)
    register_btn.click()
    #home_page.wait_page_loaded()
    assert garage_page.item(garage_page.add_car).is_presented(), "User is not registered or add car button is not displayed"
